### ISSUE TITLE
Error when parsing file with comments (`;;`)

### ISSUE THREAD

**Issue by dannyhammer** [sunsided/pddl-rs#81]
Cannot use `pddl-rs` to parse PDDL files containing comments (`;;`).

Using `pddl = "0.0.6"` in `Cargo.toml`

Code:
```rust
use pddl::{Parser, Problem};
use std::fs;

fn main() {
    let path = "./problem.pddl";
    let contents = fs::read_to_string(path).unwrap();

    let problem = Problem::from_str(&contents);

    println!("{:#?}", problem);
}
```

PDDL file (`./problem.pddl`):
```pddl
(define (problem pb1)
    (:domain air-cargo)
    (:objects
        C1 C2 P1 P2 SFO JFK
    )
    (:init
        ;; types
        (Cargo C1)
        (Cargo C2)
        (Plane P1)
        (Plane P2)
        (Airport SFO)
        (Airport JFK)

        ;; locations
        (At C1 SFO)
        (At C2 JFK)
        (At P1 SFO)
        (At P2 JFK)
    )

    (:goal
        (and (At C1 JFK) (At C2 SFO))
    )
)
```

Error printed: 
```
Err(
    Error(
        GreedyError {
            errors: [
                (
                    LocatedSpan {
                        offset: 113,
                        line: 7,
                        fragment: ";; types\n        (Cargo C1)\n        (Cargo C2)\n        (Plane P1)\n        (Plane P2)\n        (Airport SFO)\n        (Airport JFK)\n\n        ;; locations\n        (At C1 SFO)\n        (At C2 JFK)\n        (At P1 SFO)\n        (At P2 JFK)\n    )\n\n    (:goal\n        (and (At C1 JFK) (At C2 SFO))\n    )\n)",
                        extra: (),
                    },
                    Nom(
                        Tag,
                    ),
                ),
            ],
        },
    ),
)
```

**Comment by sunsided** [comment]
Hey Danny, thanks for the report - that's correct, there is no support for comments yet. I'll see to add them when I find the time for it.

**Comment by dannyhammer** [comment]
Where would a `comment` parser fit into this? I assume it would be under `parsers/utilities.rs`, similar to `ws`. I am new to `nom`, having uses `pest` before, so I am not certain of how a comment parser would be implemented, perhaps something like this?
```rust
/// A combinator that takes a parser `inner` and produces a parser that consumes
/// all leading comment characters `;` and the endline char or EOF at the end of
/// the line, returning the outputs of `inner`.
pub fn comment<'a, F, O>(inner: F) -> impl FnMut(Span<'a>) -> ParseResult<'a, O>
where
    F: FnMut(Span<'a>) -> ParseResult<'a, O>,
{
    delimited(many1(char(';')), ws(inner), alt((line_ending, eof)))
}
```

This seems to work for simple tests with strings like `; content`, `;; content`, `; content\n`, `;content`, etc.

However, I am not sure where this would be integrated so that it works throughout the parser, such as in my example above.

Thoughts?

**Comment by sunsided** [comment]
Utilities would be a good spot - I noticed you forked the repo already, but if the tests go through here on GitHub it will be fixed in #82 and I'll release a new version right away.

I had a little argument with nom about this too just now. That both `ws` and the comment parser would have to ignore spaces, which in turn interfered with `space_separated_list1` and the likes.

**Comment by sunsided** [comment]
It's available in `0.0.7` now - could you give it a try and tell me if it checks out?

**Comment by dannyhammer** [comment]
Works for all examples I was utilizing it for. I really appreciate your swiftness at acknowledging and resolving this issue.

**Comment by sunsided** [comment]
Pleasure! If you can put the library to good use, do tell - I'd be happy to hear your feedback!
